"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { emptyState,summary,pending,balance,loan,type State } from '@/lib/finance';
import { Plus,Wallet,House,ChartNoAxesCombined,CalendarDays,ArrowLeftRight,Settings,Download,Pencil,Trash2 } from 'lucide-react';
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const tabs=[['Hoje',Wallet],['Lançamentos',ArrowLeftRight],['Planejamento',CalendarDays],['Apartamento',House],['Investimentos',ChartNoAxesCombined],['Configurações',Settings]] as const;
type Collection='accounts'|'categories'|'entries'|'recurring';
type Item=Record<string,string|number>;
const titles={accounts:'Conta',categories:'Categoria',entries:'Lançamento',recurring:'Recorrência',plan:'Plano do apartamento'};
export default function Home(){
 const [s,setS]=useState<State>(emptyState),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('Hoje'),[month,setMonth]=useState(''),[search,setSearch]=useState(''),[editor,setEditor]=useState<Collection|'plan'|null>(null),[draft,setDraft]=useState<Item>({});
 useEffect(()=>{setMonth(today().slice(0,7));void load();},[]);
 async function load(){setError('');try{const r=await fetch('/api/finance',{cache:'no-store'});const b=await r.json() as {state:State,revision:number,error?:string};if(!r.ok)throw Error(b.error);setS(b.state);setRevision(b.revision);setReady(true);}catch(e){setError(e instanceof Error?e.message:'Falha de conexão.');}}
 async function save(next:State){if(busy||!ready)return false;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/finance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:next,revision})});const b=await r.json() as {revision:number,error?:string};if(!r.ok)throw Error(b.error);setS(next);setRevision(b.revision);setNotice('Dados salvos.');return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');return false;}finally{setBusy(false);}}
 function open(kind:Collection|'plan',item?:object){setEditor(kind);setError('');setDraft(item?{...item} as Item:kind==='plan'?{...s.plan}:{id:crypto.randomUUID(),name:'',description:'',amount:0,budget:0,color:'#7368ef',account:s.accounts[0]?.id||'',category:'',to:'',date:today(),asOf:today(),opening:0,type:'cash',kind:'expense',recurrence:'',day:5,start:today(),end:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!editor)return;let next:State;if(editor==='plan')next={...s,plan:draft as State['plan']};else{const list=s[editor] as unknown as Item[];next={...s,[editor]:list.some(x=>x.id===draft.id)?list.map(x=>x.id===draft.id?draft:x):[...list,draft]} as State;}if(await save(next))setEditor(null);}
 async function remove(kind:Collection,id:string){if(!confirm('Excluir este registro?'))return;if(kind==='accounts'&&(s.entries.some(e=>e.account===id||e.to===id)||s.recurring.some(r=>r.account===id))){setError('Esta conta possui lançamentos ou recorrências.');return;}if(kind==='categories'&&[...s.entries,...s.recurring].some(e=>e.category===id)){setError('Esta categoria está em uso. Altere os registros antes de excluir.');return;}await save({...s,[kind]:s[kind].filter(x=>x.id!==id)});}
 function field(key:string,label:string,type='text',options?:Array<[string,string]>){return <label key={key}>{label}{options?<select required={!['category','recurrence'].includes(key)} value={String(draft[key]??'')} onChange={e=>setDraft({...draft,[key]:e.target.value})}>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<input required={!['description','end','keys'].includes(key)} type={type} min={type==='number'?0:undefined} max={key==='day'?31:undefined} step={type==='number'?'any':undefined} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:type==='number'?Number(e.target.value):e.target.value})}/>}</label>;}
 function currency(key:string,label:string,signed=false){return <label key={key}>{label} (R$)<input required type="number" min={signed?undefined:0} step="0.01" value={Number(draft[key]??0)/100} onChange={e=>setDraft({...draft,[key]:Math.round(Number(e.target.value)*100)})}/></label>;}
 function rows(kind:Collection){return s[kind].map(x=><div className="row" key={x.id}><div><strong>{x.name}</strong><small>{'description' in x?x.description:''}{'date' in x?' · '+x.date:''}{'day' in x?' · Dia '+x.day:''}{'type' in x?' · Saldo inicial em '+x.asOf:''}</small></div><b>{'amount' in x?money(x.amount):'opening' in x?money(balance(s,x.id,month+'-31')):money(x.budget)}</b><button aria-label={'Editar '+x.name} onClick={()=>open(kind,x)}><Pencil size={16}/></button><button disabled={busy} aria-label={'Excluir '+x.name} onClick={()=>remove(kind,x.id)}><Trash2 size={16}/></button></div>);}
 function empty(){return <p className="empty">Nenhum registro. Cadastre suas informações para começar.</p>;}
 const q=summary(s,month),due=pending(s,month),schedule=loan(s.plan),investments=s.accounts.filter(a=>a.type==='investment'),benefits=s.accounts.filter(a=>a.type==='benefit'),progress=s.plan.target?Math.min(100,s.plan.saved/s.plan.target*100):0;
 const shown=s.entries.filter(e=>e.date.startsWith(month)&&(tab!=='Lançamentos'||[e.name,e.description].join(' ').toLowerCase().includes(search.toLowerCase())));
 const targetMonths=s.plan.contribution?Math.ceil(Math.max(0,s.plan.target-s.plan.saved)/s.plan.contribution):null;
 const planMonths=s.plan.keys&&month?Math.max(0,(Number(s.plan.keys.slice(0,4))-Number(month.slice(0,4)))*12+Number(s.plan.keys.slice(5,7))-Number(month.slice(5,7))):null;
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fluxo-backup.json';a.click();URL.revokeObjectURL(url);}
 return <main className="shell"><aside><a className="brand" href="#inicio"><span>f.</span> fluxo</a><nav>{tabs.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={19}/><span>{name}</span></button>)}</nav><div className="side-note">Seu dinheiro,<br/>com perspectiva.<small>Controle pessoal · BRL</small></div></aside><section className="workspace" id="inicio"><header><div><small>Seu espaço financeiro</small><h1>{tab}</h1></div><div className="toolbar"><label className="month">Mês<input aria-label="Mês de referência" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><button className="primary" disabled={!ready||busy} onClick={()=>open('entries')}><Plus size={17}/> Lançamento</button></div></header>
 {error&&<div className="error" role="alert">{error} <button onClick={load}>Recarregar dados</button></div>}{notice&&<p role="status" className="success">{notice}</p>}
 {!ready?<article className="panel"><h2>{error?'Dados indisponíveis':'Carregando seus dados…'}</h2><p>O acesso exige sua sessão do ChatGPT. Nenhum saldo fictício é exibido.</p>{error&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar novamente</a>}</article>:<>
 {tab==='Hoje'&&<><div className="metrics"><article><small>Caixa no fim do mês¹</small><strong>{money(q.actual)}</strong><span>Saldos iniciais + lançamentos</span></article><article><small>Caixa projetado</small><strong>{money(q.projected)}</strong><span>Inclui recorrências pendentes</span></article><article className="dark"><small>Livre após reservas</small><strong>{money(q.free)}</strong><span>Após reserva mínima e aporte planejado</span></article></div><div className="grid"><article className="panel"><h2>Seu mês, explicado</h2><p>¹ Caixa considera apenas contas de dinheiro, até o fim do mês selecionado.</p>{[['Caixa registrado',q.actual],['Recorrências líquidas pendentes',q.projected-q.actual],['Reserva mínima',-s.plan.reserve],['Aporte adicional planejado',-s.plan.contribution],['Disponível projetado',q.free]].map(([n,v])=><div className="row" key={n}><span>{n}</span><b>{money(Number(v))}</b></div>)}<p>Benefícios e investimentos ficam separados. Aportes já lançados devem ser descontados do aporte adicional no plano.</p><button onClick={()=>open('plan')}>Ajustar reservas e aporte</button></article><article className="panel"><h2>Apartamento</h2><small>Reserva destinada ao objetivo</small><strong className="hero-value">{money(s.plan.saved)}</strong><progress max="100" value={progress}/><p>{money(s.plan.target)} de meta · {progress.toFixed(1)}%</p><button onClick={()=>setTab('Apartamento')}>Abrir planejamento</button></article><article className="panel"><h2>Próximos compromissos</h2>{due.length?due.slice(0,8).map(r=><div className="row" key={r.id}><div><strong>{r.name}</strong><small>{r.date} · {r.kind==='income'?'Receita':'Despesa'}</small></div><b>{money(r.amount)}</b></div>):empty()}<button onClick={()=>setTab('Planejamento')}>Gerenciar recorrências</button></article><article className="panel"><h2>Orçamento por categoria</h2>{s.categories.length?s.categories.map(c=>{const spent=shown.filter(e=>e.kind==='expense'&&e.category===c.id).reduce((n,e)=>n+e.amount,0);return <div className="budget" key={c.id}><div><span>{c.name}</span><b>{money(spent)} / {money(c.budget)}</b></div><progress max={Math.max(1,c.budget)} value={spent} style={{accentColor:c.color}}/><small>{c.description}{spent>c.budget?' · Acima do limite':''}</small></div>}):empty()}</article></div></>}
 {tab==='Lançamentos'&&<article className="panel"><div className="heading"><h2>Movimentações de {month}</h2><input aria-label="Buscar lançamentos" placeholder="Buscar descrição" value={search} onChange={e=>setSearch(e.target.value)}/></div><p>Receitas, despesas e transferências entre suas contas. Pagamento de fatura deve ser transferência se as compras já foram registradas.</p>{shown.length?shown.map(e=><div className="row" key={e.id}><div><strong>{e.name}</strong><small>{e.date} · {s.accounts.find(a=>a.id===e.account)?.name} · {e.description}</small></div><span>{e.kind==='income'?'Receita':e.kind==='expense'?'Despesa':'Transferência'}</span><b>{money(e.amount)}</b><button aria-label={'Editar '+e.name} onClick={()=>open('entries',e)}><Pencil size={16}/></button><button aria-label={'Excluir '+e.name} onClick={()=>remove('entries',e.id)}><Trash2 size={16}/></button></div>):empty()}</article>}
 {tab==='Planejamento'&&<div className="grid"><article className="panel wide"><div className="heading"><h2>Receitas e gastos fixos</h2><button onClick={()=>open('recurring')}><Plus size={16}/> Recorrência</button></div><p>Valores mensais com início e fim. Dia 31 é ajustado ao último dia dos meses mais curtos.</p>{s.recurring.length?rows('recurring'):empty()}</article><article className="panel wide"><h2>Pendentes em {month}</h2><p>Ao registrar o pagamento ou recebimento, a previsão é substituída por um lançamento, sem duplicação.</p>{due.length?due.map(r=><div className="row" key={r.id}><div><strong>{r.name}</strong><small>{r.date}</small></div><b>{money(r.amount)}</b><button disabled={busy} onClick={()=>save({...s,entries:[...s.entries,{id:crypto.randomUUID(),name:r.name,description:r.description,amount:r.amount,kind:r.kind,account:r.account,to:'',category:r.category,date:r.date,recurrence:r.id}]})}>Registrar {r.kind==='income'?'recebimento':'pagamento'}</button></div>):empty()}</article><article className="panel wide"><div className="heading"><h2>Categorias e limites mensais</h2><button onClick={()=>open('categories')}><Plus size={16}/> Categoria</button></div>{s.categories.length?rows('categories'):empty()}</article></div>}
 {tab==='Apartamento'&&<div className="grid"><article className="panel"><div className="heading"><h2>Plano até as chaves</h2><button onClick={()=>open('plan')}>Editar plano</button></div><div className="row"><span>Meta total (entrada, custos e acabamento)</span><b>{money(s.plan.target)}</b></div><div className="row"><span>Já reservado</span><b>{money(s.plan.saved)}</b></div><div className="row"><span>Aporte adicional mensal</span><b>{money(s.plan.contribution)}</b></div><div className="row"><span>Falta reservar</span><b>{money(Math.max(0,s.plan.target-s.plan.saved))}</b></div><p>{targetMonths===null?'Informe o aporte para estimar o prazo.':targetMonths+' meses de aportes para atingir a meta, sem rendimentos.'}</p><p>{s.plan.keys?'Chaves previstas: '+s.plan.keys:'Data das chaves não informada.'}</p>{planMonths!==null&&<div className="row"><span>Estimativa até as chaves</span><b>{money(s.plan.saved+planMonths*s.plan.contribution)}</b></div>}<p>A reserva do objetivo é uma destinação do patrimônio, não é somada novamente ao saldo das contas.</p></article><article className="panel"><h2>Simulação do financiamento</h2><p>{s.plan.system} · {s.plan.annual}% a.a. efetivos · {s.plan.term} meses</p><div className="row"><span>Principal</span><b>{money(s.plan.principal)}</b></div><div className="row"><span>Primeira parcela estimada</span><b>{money(schedule[0].payment)}</b></div><div className="row"><span>Última parcela estimada</span><b>{money(schedule.at(-1)!.payment)}</b></div><div className="row"><span>Total das parcelas</span><b>{money(schedule.reduce((n,r)=>n+r.payment,0))}</b></div><p>Simulação com taxa constante, sem TR, correções, carência ou seguros variáveis. Encargos mensais informados são incluídos. Não substitui a planilha do contrato e não lança parcelas automaticamente no caixa.</p><button onClick={()=>open('plan')}>Alterar cenário</button></article><article className="panel wide"><h2>Evolução da dívida · primeiros 12 meses</h2>{schedule.slice(0,12).map(r=><div className="row" key={r.month}><span>Parcela {r.month}</span><b>{money(r.payment)}</b><small>Saldo devedor {money(r.debt)}</small></div>)}</article></div>}
 {tab==='Investimentos'&&<div className="grid"><article className="panel"><h2>Patrimônio em investimentos</h2><strong className="hero-value">{money(investments.reduce((n,a)=>n+balance(s,a.id,month+'-31'),0))}</strong><p>Posições manuais. Sem cotações, rentabilidade automática ou conexão com corretoras.</p><button onClick={()=>{open('accounts');setDraft(d=>({...d,type:'investment'}));}}>Adicionar investimento</button>{investments.map(a=><div className="row" key={a.id}><strong>{a.name}</strong><b>{money(balance(s,a.id,month+'-31'))}</b><button onClick={()=>open('accounts',a)}>Editar</button></div>)}</article><article className="panel"><h2>Benefícios disponíveis</h2><p>Saldo restrito a benefícios, separado do dinheiro livre.</p>{benefits.length?benefits.map(a=><div className="row" key={a.id}><strong>{a.name}</strong><b>{money(balance(s,a.id,month+'-31'))}</b></div>):empty()}</article></div>}
 {tab==='Configurações'&&<div className="grid"><article className="panel wide"><div className="heading"><h2>Contas e saldos iniciais</h2><button onClick={()=>open('accounts')}><Plus size={16}/> Conta</button></div><p>Informe o saldo no início da data escolhida. Registre apenas movimentações dessa data em diante.</p>{s.accounts.length?rows('accounts'):empty()}</article><article className="panel"><h2>Integrações</h2>{['BTG','Nubank','iFood Benefícios'].map(n=><div className="row" key={n}><strong>{n}</strong><span className="badge">Desconectado</span></div>)}<p>Conectores serão implementados manualmente no código. Nenhuma senha, chave ou consulta bancária é usada nesta versão. Importação OFX/CSV ainda não disponível.</p></article><article className="panel"><h2>Seus dados</h2><p>Dados salvos no servidor, separados por usuário. Exporte uma cópia para seu controle.</p><button onClick={exportData}><Download size={16}/> Exportar JSON</button><p>O arquivo exportado contém seus dados financeiros. Guarde em local privado.</p></article></div>}
 </>}
 </section><Dialog open={!!editor} onOpenChange={v=>{if(!v&&!busy)setEditor(null);}}><DialogContent className="edit-dialog"><DialogTitle>{editor?titles[editor]:''}</DialogTitle><DialogDescription>Os dados só são alterados após salvar. Valores em reais.</DialogDescription><form onSubmit={submit}><div className="fields">
 {editor!=='plan'&&field('name','Nome')}
 {(editor==='categories'||editor==='entries'||editor==='recurring')&&field('description','Descrição')}
 {editor==='categories'&&<>{currency('budget','Limite mensal')}{field('color','Cor','color')}</>}
 {editor==='accounts'&&<>{field('type','Tipo','text',[['cash','Dinheiro / conta corrente'],['benefit','Benefícios'],['investment','Investimento']])}{currency('opening','Saldo inicial',true)}{field('asOf','Data do saldo inicial','date')}</>}
 {(editor==='entries'||editor==='recurring')&&<>{currency('amount','Valor')}{field('kind','Tipo','text',editor==='entries'?[['expense','Despesa'],['income','Receita'],['transfer','Transferência']]:[['expense','Despesa'],['income','Receita']])}{field('account','Conta','text',[['','Selecione'],...s.accounts.map(a=>[a.id,a.name] as [string,string])])}{field('category','Categoria','text',[['','Sem categoria'],...s.categories.map(c=>[c.id,c.name] as [string,string])])}</>}
 {editor==='entries'&&<>{field('date','Data','date')}{draft.kind==='transfer'&&field('to','Conta de destino','text',[['','Selecione'],...s.accounts.map(a=>[a.id,a.name] as [string,string])])}{field('recurrence','Vincular à recorrência (evita duplicação)','text',[['','Sem vínculo'],...s.recurring.map(r=>[r.id,r.name] as [string,string])])}</>}
 {editor==='recurring'&&<>{field('day','Dia do vencimento','number')}{field('start','Início','date')}{field('end','Fim (opcional)','date')}</>}
 {editor==='plan'&&<>{currency('reserve','Reserva mínima de caixa')}{currency('target','Meta do apartamento')}{currency('saved','Já reservado para apartamento')}{currency('contribution','Aporte adicional mensal')}{field('keys','Data das chaves (opcional)','date')}{currency('principal','Valor financiado')}{field('annual','Taxa anual efetiva (%)','number')}{field('term','Prazo em meses','number')}{field('system','Amortização','text',[['SAC','SAC'],['PRICE','Price']])}{currency('fees','Encargos mensais fixos')}</>}
 </div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy} type="submit">{busy?'Salvando…':'Salvar'}</button></form></DialogContent></Dialog></main>;
}
